# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv run install
    - name: Test 
      run: |
        pipenv run test
    - name: Pyinstaller
      run: |
        pipenv run pyinstaller torrenttv.spec
    - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: dist/app.exe
