name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Set up Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv run install
    - name: Test
      run: |
        pipenv run test
    - name: Build
      run: |
        pipenv run build
    - name: Get short SHA
        run: |
          echo "::set-env name=GIT_SHA_SHORT::$(git rev-parse --short $GITHUB_SHA)"
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: TorrentTV-${{ env.GIT_SHA_SHORT }}
        path: dist/torrenttv.exe
